import argparse


def config():
    parser = argparse.ArgumentParser()
    parser.add_argument('--language_path', type=str, default="/app/dsl/language.json", help='path to the language.json')
    parser.add_argument('--catalogue_path', type=str, default="/app/dsl/catalogue.json", help='path to the catalogue.json')
    parser.add_argument('--checkpoint_path', type=str, default="/app/checkpoints", help = "path to the checkpoint folder")
    parser.add_argument('--epoch', type=int, default=100, help = "number of epochs")
    parser.add_argument('--BS', type=int, default=100, help = "specify the batch size")
    parser.add_argument('--dim', type=int, default=512, help = "specify the dimention for xtransformer")
    parser.add_argument('--depth', type=int, default=6, help = "specify the depth for xtransformer")
    parser.add_argument('--head', type=int, default=8, help = "specify the number of head in xtransformer decoder")
    parser.add_argument('--WWL', type=float, default=1, help = "specify the weight for sequence's weight in the loss")
    parser.add_argument('--model_name', type=str, default="GearFormer")
    parser.add_argument('--lr', type=float, default=0.0001 , help = "learning rat for optimizer")
    parser.add_argument('--if_weight', type=bool, default=False, help = "pass weight as input to the model if true - it's always false in current version")
    parser.add_argument('--encoder_checkpoint_name', type=str, default="GearFormer_0.0001_18_encoder.dict" , help = "name of the encoder checkpoint")
    parser.add_argument('--decoder_checkpoint_name', type=str, default="GearFormer_0.0001_18_decoder.dict" , help = "name of the decoder checkpoint")
    parser.add_argument('--req_name', type=str, default="speed", choices=["speed", "pos"])
    parser.add_argument('--aug_data_type', type=str, default="pref", choices=["pref", "pareto"])
    parser.add_argument('--N', type=int, help = "used for Pareto experiments")
    parser.add_argument('--input_size', type=int, default=8)
    parser.add_argument('--max_length', type=int, default=21)
    parser.add_argument('--num_threads_sim', type=int, default=10)

    parser.add_argument('--gearformer_val_data', type=str, default="/app/data/gearformer_data/val_data.csv")
    parser.add_argument('--gearformer_test_data', type=str, default="/app/data/gearformer_data/test_data.csv")
    parser.add_argument('--sft_data', type=str, default="/app/data/esimft_data/sft.pkl")
    parser.add_argument('--pref_data', type=str, default="/app/data/esimft_data/pref.pkl")
    parser.add_argument('--simft_test_data', type=str, default="/app/data/esimft_data/simft_test.pkl")
    parser.add_argument('--pareto_test_data', type=str, default="/app/data/esimft_data/pareto_test.pkl")
    parser.add_argument('--ric_aug_data', type=str, default="/app/data/esimft_data/ric_aug.pkl")
    parser.add_argument('--ric_train_data', type=str, default="/app/data/esimft_data/ric_train.pkl")
    parser.add_argument('--ric_val_data', type=str, default="/app/data/esimft_data/ric_val.pkl")
    parser.add_argument('--pareto_test_aug_data', type=str, default="/app/data/esimft_data/pareto_test_aug.pkl")

    parser.add_argument('--simft_test_ratio', type=float, default=0.1)
    parser.add_argument('--sft_val_ratio', type=float, default=0.1)
    parser.add_argument('--pref_val_ratio', type=float, default=0.1)

    parser.add_argument('--gf_data_sim_input_start_idx', type=int, default=2)
    parser.add_argument('--gf_data_sim_input_end_idx', type=int, default=9)
    parser.add_argument('--gf_data_req_speed_idx', type=int, default=4)
    parser.add_argument('--gf_data_req_pos_idx', type=int, nargs="+", default=[5, 6, 7])

    parser.add_argument('--pareto_exp_num_problems', type=int, default=30)

    parser.add_argument('--pareto_exp_data_path', type=str, help = "path to the pkl file generated by pareto_exp.py")

    args = parser.parse_args()
    return args
